# Push binaries to Quay.io, when a new release is created
name: oadp-cli binaries image push

on:
  push:
    tags:
      - 'v*'

# Check out code, podman login, run podman build, push to 
jobs:
  push-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Podman login
        run: podman login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Podman build and tag
        run: |
          # Create manifest
          podman manifest create oadp-cli-binaries

          podman build \
            --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
            --manifest oadp-cli-binaries \
            -f Dockerfile.download \ 
            .
      
      - name: Podman push version tag
        run: podman manifest push oadp-cli-binaries quay.io/konveyor/oadp-cli-binaries:${{ github.ref_name }}
      
      - name: Podman push latest tag
        run: podman manifest push oadp-cli-binaries quay.io/konveyor/oadp-cli-binaries:latest