# Push binaries to Quay.io, when a new release is created
name: oadp-cli binaries image push

on:
  push:
    tags:
      - 'v*'
  pull_request:
    

# Check out code, podman login, run podman build, push to 
jobs:
  
  multi-arch-build:
    name: Multi-Arch Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      
      - name: Build Image
        id: build_image_multiarch
        uses: redhat-actions/buildah-build@v2
        with:
          image: quay.io/konveyor/oadp-cli-binaries
          tags: ${{ github.ref_type == 'tag' && format('latest {0}', github.ref_name) || 'test' }}
          archs: amd64,arm64,ppc64le,s390x
          containerfiles: |
            ./Containerfile.download

      - name: Echo Outputs
        run: |
          echo "Image: ${{ steps.build_image_multiarch.outputs.image }}"
          echo "Tags: ${{ steps.build_image_multiarch.outputs.tags }}"
          echo "Tagged Image: ${{ steps.build_image_multiarch.outputs.image-with-tag }}"
    
      - name: Check images created
        run: buildah images | grep 'quay.io/konveyor/oadp-cli-binaries'

      - name: Check manifest
        run: |
          set -x
          buildah manifest inspect ${{ steps.build_image_multiarch.outputs.image-with-tag }}
      - name: Buildah login
        run: buildah login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io
      
      - name: Buildah push version tag
        if: startsWith(github.ref_name, 'v')
        run: buildah manifest push ${{ steps.build_image_multiarch.outputs.image-with-tag }} quay.io/konveyor/oadp-cli-binaries:${{ github.ref_name }}
      
      - name: Buildah push latest tag
        if: startsWith(github.ref_name, 'v')
        run: buildah manifest push ${{ steps.build_image_multiarch.outputs.image-with-tag }} quay.io/konveyor/oadp-cli-binaries:latest